# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponentes',
            name='olio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='talleres_disponibles',
            field=models.IntegerField(choices=[(3, 'Taller 3'), (1, 'Taller 1'), (2, 'Taller 2')]),
        ),
    ]
