# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=255)),
                ('institucion_de_procedencia', models.CharField(max_length=255)),
                ('talleres_disponibles', models.IntegerField(choices=[(1, 'Taller 1'), (2, 'Taller 2'), (3, 'Taller 3')])),
            ],
            options={
                'verbose_name': 'Asistentes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ponentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('a1_nombre', models.CharField(max_length=255)),
                ('a1_apellido_paterno', models.CharField(max_length=255)),
                ('a1_apellido_materno', models.CharField(max_length=255)),
                ('a1_correo_electronico', models.EmailField(max_length=254)),
                ('a1_telefono', models.CharField(max_length=255)),
                ('a1_institucion_de_procedencia', models.CharField(max_length=255)),
                ('a2_nombre', models.CharField(max_length=255)),
                ('a2_apellido_paterno', models.CharField(max_length=255)),
                ('a2_apellido_materno', models.CharField(max_length=255)),
                ('a3_nombre', models.CharField(max_length=255)),
                ('a3_apellido_paterno', models.CharField(max_length=255)),
                ('a3_apellido_materno', models.CharField(max_length=255)),
                ('documentos', models.FileField(blank=True, null=True, upload_to=landing.models.content_file_name)),
            ],
            options={
                'verbose_name': 'Ponentes',
                'ordering': ('titulo',),
            },
        ),
    ]
