# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171218_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponentes',
            old_name='olio',
            new_name='folio',
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='talleres_disponibles',
            field=models.IntegerField(choices=[(1, 'La Práctica de la Plena Consciencia en el Salón de Clases.'), (5, 'Desarrollo del Pensamiento Crítico a través de la Filosofía para Niños.'), (3, 'Estrategias Docentes para el Desarrollo de Habilidades para la Vida.'), (6, 'El Debate como Estrategia Didáctica para Desarrollar Habilidades Argumentativas en los Estudiantes.'), (8, 'Aplicación en el Aula del Aprendizaje Basado en Problemas a través de la Historia de Casos.'), (2, 'Manejo del Estrés en la Tutoría Individual y Grupal través de la Atención Plena.'), (10, 'Habilidades Contemplativas, Género y Violencia.'), (9, 'El uso del Portafolio como Estrategia de Enseñanza y Evaluación.'), (4, 'Grupos Cooperativos para el Desarrollo de Habilidades Sociales en el Aula.'), (7, 'Aplicación del Aprendizaje Basado en Proyectos en el Salón de Clases.')]),
        ),
        migrations.AlterField(
            model_name='ponentes',
            name='a2_apellido_materno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ponentes',
            name='a2_apellido_paterno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ponentes',
            name='a2_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ponentes',
            name='a3_apellido_materno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ponentes',
            name='a3_apellido_paterno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ponentes',
            name='a3_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
