# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_asistentes_ponentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponentes',
            old_name='documentos',
            new_name='documento',
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='talleres_disponibles',
            field=models.IntegerField(choices=[(3, 'Taller 3'), (2, 'Taller 2'), (1, 'Taller 1')]),
        ),
    ]
