# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180305_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='talleres_disponibles',
            field=models.IntegerField(choices=[(8, 'Aplicación en el Aula del Aprendizaje Basado en Problemas a través de la Historia de Casos.'), (5, 'Desarrollo del Pensamiento Crítico a través de la Filosofía para Niños.'), (2, 'Manejo del Estrés en la Tutoría Individual y Grupal través de la Atención Plena.'), (1, 'La Práctica de la Plena Consciencia en el Salón de Clases.'), (4, 'Grupos Cooperativos para el Desarrollo de Habilidades Sociales en el Aula.'), (9, 'El uso del Portafolio como Estrategia de Enseñanza y Evaluación.'), (10, 'Habilidades Contemplativas, Género y Violencia.'), (7, 'Aplicación del Aprendizaje Basado en Proyectos en el Salón de Clases.'), (3, 'Estrategias Docentes para el Desarrollo de Habilidades para la Vida.'), (6, 'El Debate como Estrategia Didáctica para Desarrollar Habilidades Argumentativas en los Estudiantes.')]),
        ),
    ]
