# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20171218_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponentes',
            name='lineas_tematicas',
            field=models.IntegerField(blank=True, choices=[(1, 'Análisis teórico (CCAT)'), (2, 'Investigación empírica en educación (CCIE)'), (3, 'Investigación empírica en la salud (CCIS)'), (4, 'Análisis teórico sobre el desarrollo de habilidades para la vida. (HVAT)'), (5, 'Estrategias de enseñanza y desarrollo de habilidades para la vida (IEHVE)'), (6, 'Habilidades socioemocionales (IEHSE)'), (7, 'Habilidades cognoscitivas (IEHC)'), (8, 'Habilidades de investigación en ciencias(IEHIC)'), (9, 'Habilidades de investigación en humanidades (IEHIH)'), (10, 'Evaluación de habilidades para la vida (IEEHV)')], null=True),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='talleres_disponibles',
            field=models.IntegerField(choices=[(1, 'Taller 1'), (3, 'Taller 3'), (2, 'Taller 2')]),
        ),
    ]
